### ISSUE TITLE
Request: Support floating point numbers

### ISSUE THREAD

**Issue by AndydeCleyre** [Kevinpgalligan/bs#1] opened 2023-05-02 17:04 UTC
Context:
```console
$ bs 60
[from decimal]
  binary      111100
  hexadecimal 3C
  octal       74

...
```

Current:
```console
$ bs 60.5
ERROR! Unsupported base, must be <=16.
```
Requested:
```console
$ bs 60.5
[from decimal]
  binary      111100.1
  hexadecimal 3C.8
  octal       74.4

...
```

**Comment by Kevinpgalligan** [comment] 2023-05-02 17:27
Hey, thanks for the feedback! This shouldn't be hard to implement. Do you have a use case in mind? Floating point numbers are stored in special formats, so it wouldn't be that useful for, e.g., investigating a binary file.

**Comment by AndydeCleyre** [comment] 2023-05-02 17:36
Nothing serious or professional, I just sometimes do nonsense/math-enthusiast work with base 12, 60, etc.

**Comment by Kevinpgalligan** [comment] 2023-05-02 18:25
Okay, sure! I'll take a look at it when I get the chance. I'm curious how you came across this, by the way, as I made no effort to advertise it besides linking it on my website!

**Comment by AndydeCleyre** [comment] 2023-05-02 18:35
Thanks!

Someone [commented in r/commandline](https://old.reddit.com/r/commandline/comments/135iay2/easiest_way_to_do_number_base_conversions_in_the/) about your project today.

**Comment by Kevinpgalligan** [comment] 2023-05-08 15:12
I added support for this in the latest commit, will now upload the latest version to PyPI.

**Comment by Kevinpgalligan** [comment] 2023-05-08 15:13
Let me know if it doesn't work for some reason.

**Comment by AndydeCleyre** [comment] 2023-05-08 18:48
Thanks! It's not quite right yet, though. Checking the original example against bs 1.0.1:

Expected:

```console
$ bs 60.5
[from decimal]
  binary      111100.1
  hexadecimal 3C.8
  octal       74.4

...
```

Current:

```console
$ bs 60.5
[from decimal]
  binary      111100.101
  hexadecimal 3C.5
  octal       74.5

...
```

**Comment by Kevinpgalligan** [comment] 2023-05-10 11:07
Why is the expected version correct? 5 is 101 in binary, 5 in hex and 5 in octal. Should the fractional part be treated differently?

**Comment by AndydeCleyre** [comment] 2023-05-10 18:04
My input is interpreted as decimal, that is six tens plus five tenths, or six tens plus one half. 

So the goal should not be to turn the `5` from `.5` (which represents `5/10`, or one half), to the representation of 5 in each other base, but to represent one half in each other base.

**Comment by Kevinpgalligan** [comment] 2023-05-11 09:13
Hmmm, gotcha. I'll have to think about how to implement this.

**Comment by Kevinpgalligan** [comment] 2023-05-12 19:15
I've implemented code that, given the fractional part of a number as an integer (e.g. `0.1` in binary becomes the integer `5` in decimal), can output the equivalent fraction in any base. The problem is that not all fractions in other bases can be represented in decimal with a finite number of digits, e.g. 0.1 in base 3. To work around that I may have to add a precision variable.

**Comment by Kevinpgalligan** [comment] 2023-05-12 19:55
Okay, finally got it working!

Your example:

```
$ bs 0.5
[from decimal]
  binary      0.1
  hexadecimal 0.8
  octal       0.4

[from hexadecimal]
  decimal     0.3125
  binary      0.0101
  octal       0.24

[from octal]
  decimal     0.625
  binary      0.101
  hexadecimal 0.A
```


And the new interface for setting precision:

```
$ bs --precision 10 --from 3 --to decimal 0.1
0.3333333333
```

**Comment by Kevinpgalligan** [comment] 2023-05-12 20:01
...and now I've uploaded the latest version to PyPI. Happy base converting!

**Comment by Kevinpgalligan** [comment] 2023-05-12 20:10
Welp, this seizes up. Need to debug.

```
bs -f 36 0.z
[from base-36]
  decimal     0.97222222
```

**Comment by Kevinpgalligan** [comment] 2023-05-12 22:13
The problem is that I wasn't using the precision at the output stage. Should be fixed now, and hopefully that's the last of the bugs.

**Closed as completed by Kevinpgalligan** 2023-05-12 22:13 UTC
